# Generated by Django 6.0.2 on 2026-02-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseapp.basemodel')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_role', models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('user', 'user')], default='user', max_length=20)),
                ('user_status', models.CharField(choices=[('new', 'new'), ('code_verify', 'code_verify'), ('details', 'details'), ('picture', 'picture')], default='new', max_length=20)),
                ('auth_type', models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone')], default='via_email', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_profile_photos/')),
            ],
            options={
                'abstract': False,
            },
            bases=('baseapp.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseapp.basemodel')),
                ('code', models.CharField(max_length=4)),
                ('auth_type', models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('expiry_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_verifications', to='accounts.customuser')),
            ],
            bases=('baseapp.basemodel',),
        ),
    ]
