# Generated by Django 6.0.2 on 2026-02-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('manager', 'manager'), ('user', 'user')], default='user', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('code_verify', 'code_verify'), ('details', 'details'), ('picture', 'picture'), ('done', 'done')], default='new', max_length=20, null=True),
        ),
    ]
