# Generated by Django 6.0.2 on 2026-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('via_email', 'via_email'), ('via_phone', 'via_phone'), ('via_username', 'via_username')], default='via_email', max_length=20, null=True),
        ),
    ]
