# Generated by Django 6.0.1 on 2026-01-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status_alter_account_type'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.incomecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
