# Generated by Django 5.2.8 on 2025-12-07 15:10

import markaz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=markaz.models.upload_to),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=markaz.models.upload_to),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
